---
Name: coreconfig
---
Upload:
  # Replace an existing file rather than renaming the new one.
  replaceFile: false
MySQLDatabase:
  connection_charset: utf8
HTTP:
  cache_control:
    max-age: 0
    must-revalidate: "true"
    no-transform: "true"