---
Name: coreconfig
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Core\Manifest\ResourceURLGenerator:
    class: SilverStripe\Control\SimpleResourceURLGenerator
    properties:
      NonceStyle: mtime
SilverStripe\Control\HTTP:
  cache_control:
    max-age: 0
    must-revalidate: "true"
    no-transform: "true"
  vary: "Cookie, X-Forwarded-Protocol, User-Agent, Accept"
LeftAndMain:
  dependencies:
    versionProvider: %$VersionProvider
SilverStripe\Core\Manifest\VersionProvider:
  modules:
    silverstripe/framework: Framework
